# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM python:3.11-slim

WORKDIR /app

# Install runtime dependencies
COPY pyproject.toml .
RUN pip install --no-cache-dir fastmcp requests

# Copy source
COPY . .

ENTRYPOINT ["python", "main.py"]
